apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-powershell-assistant-data
  namespace: ai-powershell-assistant
  labels:
    app.kubernetes.io/name: ai-powershell-assistant
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-powershell-assistant-logs
  namespace: ai-powershell-assistant
  labels:
    app.kubernetes.io/name: ai-powershell-assistant
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-powershell-assistant-models
  namespace: ai-powershell-assistant
  labels:
    app.kubernetes.io/name: ai-powershell-assistant
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd