apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-powershell-assistant-config
  namespace: ai-powershell-assistant
  labels:
    app.kubernetes.io/name: ai-powershell-assistant
    app.kubernetes.io/component: config
data:
  config.yaml: |
    version: "1.0.0"
    platform: "auto"
    
    server:
      host: "0.0.0.0"
      port: 8000
      max_concurrent_sessions: 50
      session_timeout: 3600
      enable_cors: true
      cors_origins: ["*"]
    
    mcp_server:
      name: "AI PowerShell Assistant"
      version: "1.0.0"
      enable_natural_language_tool: true
      enable_execute_command_tool: true
      enable_system_info_tool: true
      max_request_size: 10485760
      request_timeout: 300
    
    powershell:
      executable: "pwsh"
      version_preference: "core"
      default_timeout: 60
      max_output_size: 1048576
      encoding: "utf-8"
    
    ai_model:
      type: "llama-cpp"
      model_path: "/app/models/llama-7b-chat.bin"
      context_length: 4096
      temperature: 0.5
      max_tokens: 256
      batch_size: 8
      threads: 4
      gpu_layers: 0
    
    security:
      sandbox_enabled: true
      docker_image: "mcr.microsoft.com/powershell:ubuntu-20.04"
      sandbox_timeout: 300
      sandbox_memory_limit: "512m"
      sandbox_cpu_limit: "1.0"
      whitelist_enabled: true
      whitelist_path: "/app/config/security-rules.yaml"
      require_confirmation_for_admin: true
      audit_enabled: true
    
    storage:
      data_directory: "/app/data"
      log_directory: "/app/logs"
      backup_enabled: true
      backup_interval: 86400
      retention_days: 30
    
    logging:
      level: "INFO"
      format: "json"
      outputs: ["file", "console"]
      correlation_tracking: true
      performance_monitoring: true
      audit_trail: true
      sensitive_data_masking: true

  security-rules.yaml: |
    version: "1.0.0"
    last_updated: "2024-01-15T10:30:45Z"
    
    global:
      default_action: "block"
      risk_threshold: "medium"
      enable_learning: true
    
    categories:
      safe_commands:
        description: "Safe read-only commands"
        action: "allow"
        risk_level: "low"
        patterns:
          - "^Get-"
          - "^Show-"
          - "^Test-Connection"
          - "^Measure-"
      
      administrative_commands:
        description: "Administrative commands requiring confirmation"
        action: "confirm"
        risk_level: "high"
        patterns:
          - "^Set-"
          - "^New-"
          - "^Remove-"
          - "^Start-Service"
          - "^Stop-Service"
          - "^Restart-"
      
      dangerous_commands:
        description: "Potentially dangerous commands"
        action: "block"
        risk_level: "critical"
        patterns:
          - "Remove-Item.*-Recurse"
          - "Format-Volume"
          - "Clear-Host"
          - "rm -rf"
          - "del /s"
    
    rules:
      - name: "allow_process_management"
        pattern: "^Get-Process"
        action: "allow"
        risk_level: "low"
        description: "Allow process listing"
      
      - name: "block_system_shutdown"
        pattern: "Stop-Computer|Restart-Computer|shutdown"
        action: "block"
        risk_level: "critical"
        description: "Block system shutdown commands"
      
      - name: "confirm_service_changes"
        pattern: "(Start|Stop|Restart)-Service"
        action: "confirm"
        risk_level: "high"
        description: "Require confirmation for service changes"

  logging.yaml: |
    version: "1.0.0"
    
    root:
      level: "INFO"
      handlers: ["console", "file", "audit"]
    
    handlers:
      console:
        type: "console"
        level: "INFO"
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      
      file:
        type: "rotating_file"
        level: "DEBUG"
        filename: "/app/logs/app.log"
        max_bytes: 10485760
        backup_count: 5
        format: "%(asctime)s - %(name)s - %(levelname)s - %(correlation_id)s - %(message)s"
      
      audit:
        type: "rotating_file"
        level: "INFO"
        filename: "/app/logs/audit.log"
        max_bytes: 52428800
        backup_count: 10
        format: "%(asctime)s - AUDIT - %(correlation_id)s - %(message)s"
    
    loggers:
      ai_engine:
        level: "INFO"
        handlers: ["file"]
        propagate: false
      
      security_engine:
        level: "WARNING"
        handlers: ["file", "audit"]
        propagate: false
      
      execution_engine:
        level: "INFO"
        handlers: ["file", "audit"]
        propagate: false
    
    audit:
      enabled: true
      events:
        - "user_input"
        - "ai_processing"
        - "security_validation"
        - "command_execution"
        - "error_events"
      correlation_tracking: true
      performance_metrics: true