# Development Configuration Template
# AI PowerShell Assistant - Development Environment

version: "1.0.0"
platform: "auto"

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  max_concurrent_sessions: 5
  session_timeout: 1800
  enable_cors: true
  cors_origins: ["*"]

# MCP Server Settings
mcp_server:
  name: "AI PowerShell Assistant (Dev)"
  version: "1.0.0-dev"
  enable_natural_language_tool: true
  enable_execute_command_tool: true
  enable_system_info_tool: true
  max_request_size: 10485760
  request_timeout: 600

# PowerShell Configuration
powershell:
  executable: "auto"
  version_preference: "any"
  default_timeout: 120
  max_output_size: 2097152
  encoding: "utf-8"

# AI Model Configuration
ai_model:
  type: "llama-cpp"
  model_path: "./models/llama-7b-chat.bin"
  context_length: 2048
  temperature: 0.9
  max_tokens: 1024
  batch_size: 4
  threads: 4
  gpu_layers: 0  # Disable GPU in development

# Security Configuration
security:
  sandbox_enabled: false  # Disable sandbox for faster development
  docker_image: "mcr.microsoft.com/powershell:ubuntu-20.04"
  sandbox_timeout: 300
  sandbox_memory_limit: "256m"
  sandbox_cpu_limit: "0.5"
  whitelist_enabled: false  # Disable security restrictions in dev
  whitelist_path: "./config/security-rules.yaml"
  require_confirmation_for_admin: false
  audit_enabled: true

# Storage Configuration
storage:
  data_directory: "./data"
  log_directory: "./logs"
  backup_enabled: false
  backup_interval: 86400
  retention_days: 7

# Logging Configuration
logging:
  level: "DEBUG"
  format: "text"
  outputs: ["console", "file"]
  correlation_tracking: true
  performance_monitoring: true
  audit_trail: true
  sensitive_data_masking: false

# Performance Configuration
performance:
  cache_enabled: true
  cache_size: 1000
  cache_ttl: 1800
  connection_pool_size: 5
  garbage_collection_interval: 600
  memory_cleanup_interval: 1200

# Development-specific settings
development:
  auto_reload: true
  debug_mode: true
  profiling_enabled: true
  test_mode: false