# AI PowerShell 智能助手 - 默认配置文件
# 
# 本配置文件包含所有可配置的选项及其默认值
# 修改后需要重启应用才能生效

# ============================================
# AI 引擎配置
# ============================================
ai:
  # AI 提供商类型
  # 可选值: local, ollama, openai, azure
  provider: ollama
  
  # AI 模型名称
  # 对于 local: llama, gpt2 等
  # 对于 ollama: llama2, codellama, qwen3:30b 等
  model_name: qwen3:30b
  
  # Ollama 服务地址
  # 默认为本地服务
  ollama_url: http://localhost:11434
  
  # 生成温度 (0.0 - 2.0)
  # 较低的值使输出更确定，较高的值使输出更随机
  temperature: 0.7
  
  # 最大生成 token 数 (1 - 4096)
  max_tokens: 256
  
  # 是否启用 AI 提供商
  # 设置为 true 才会使用 AI 模型，否则只使用规则匹配
  use_ai_provider: true
  
  # 是否启用翻译缓存
  # 启用后可以加快重复查询的响应速度
  cache_enabled: true
  
  # 缓存大小（条目数）
  cache_size: 100

# ============================================
# 安全引擎配置
# ============================================
security:
  # 是否启用沙箱执行
  # 启用后命令将在隔离环境中执行（需要 Docker）
  sandbox_enabled: false
  
  # 是否需要用户确认
  # 启用后执行命令前会要求用户确认
  require_confirmation: true
  
  # 白名单模式
  # 可选值: strict (严格), moderate (中等), permissive (宽松)
  whitelist_mode: strict
  
  # 危险命令模式列表
  # 使用正则表达式匹配危险命令
  dangerous_patterns:
    - Remove-Item.*-Recurse.*-Force  # 递归强制删除
    - Format-Volume                   # 格式化磁盘
    - Remove-Item.*C:\\              # 删除系统盘文件
    - Stop-Computer                   # 关机
    - Restart-Computer                # 重启
    - Clear-RecycleBin.*-Force       # 清空回收站
    - Remove-Item.*\\Windows         # 删除 Windows 目录
    - Set-ExecutionPolicy            # 修改执行策略
  
  # 安全命令前缀列表
  # 以这些前缀开头的命令被认为是安全的
  safe_prefixes:
    - Get-      # 获取信息
    - Show-     # 显示信息
    - Test-     # 测试
    - Find-     # 查找
    - Select-   # 选择
    - Where-    # 过滤
    - echo      # 输出
    - Write-    # 写入输出
  
  # 自定义安全规则
  # 可以添加额外的安全规则
  custom_rules: []

# ============================================
# 执行引擎配置
# ============================================
execution:
  # 命令执行超时时间（秒）
  # 范围: 1 - 300
  timeout: 30
  
  # 输出编码格式
  # Windows 中文系统建议使用 gbk
  # Linux/macOS 建议使用 utf-8
  encoding: gbk
  
  # 平台类型
  # 可选值: auto (自动检测), windows, linux, macos
  platform: auto
  
  # PowerShell 可执行文件路径（可选）
  # 如果不指定，系统会自动检测
  powershell_path: null
  
  # 是否自动检测 PowerShell
  # 启用后会自动查找 pwsh 或 powershell
  auto_detect_powershell: true

# ============================================
# 日志配置
# ============================================
logging:
  # 日志级别
  # 可选值: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  
  # 日志文件路径
  # 设置为 null 则不写入文件
  file: logs/assistant.log
  
  # 日志文件最大大小
  # 支持单位: KB, MB, GB
  max_size: 10MB
  
  # 日志文件备份数量
  # 当日志文件达到最大大小时，会创建备份
  backup_count: 5
  
  # 日志格式
  # 使用 Python logging 格式字符串
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  
  # 是否输出到控制台
  console_output: true

# ============================================
# 存储配置
# ============================================
storage:
  # 存储基础路径
  # 支持 ~ 表示用户主目录
  base_path: ~/.ai-powershell
  
  # 历史记录文件名
  history_file: history.json
  
  # 配置文件名
  config_file: config.yaml
  
  # 缓存目录名
  cache_dir: cache
  
  # 最大历史记录数量
  # 超过此数量会自动清理旧记录
  max_history_size: 1000

# ============================================
# 上下文管理配置
# ============================================
context:
  # 最大上下文深度
  # 保留最近 N 条命令作为上下文
  # 范围: 1 - 50
  max_context_depth: 5
  
  # 会话超时时间（秒）
  # 超过此时间未活动的会话会被清理
  session_timeout: 3600
  
  # 是否启用学习功能
  # 启用后系统会从历史记录中学习
  enable_learning: true
